services:
  daily-relay:
    build:
      context: .
      network: host
    network_mode: host
    volumes:
      - ./data:/app/data
      - ./public:/app/public
      - ./src:/app/src
    restart: always
