services:
  daily-relay:
    build:
      context: .
      network: host
    network_mode: host
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./public:/app/public
      - ./src:/app/src
      - ./sources.yaml:/app/sources.yaml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
