services:
  daily-relay:
    build:
      context: .
      network: host
    network_mode: host
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./public:/app/public
      - ./src:/app/src
      - ./tests:/app/tests
      - ./sources.yaml:/app/sources.yaml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # This anonymous volume ensures container-built modules aren't overwritten by host files
      - /app/node_modules
    restart: always
