/**
 * Google Drive Publisher Test Script
 * 
 * Verifies OAuth credentials and creates/updates a test document in Google Drive.
 */
require('dotenv').config();
const { publishBriefing } = require('../src/publishers/googleDrivePublisher');

async function runTest() {
  console.log("=== Starting Google Drive Publisher Test ===");
  
  const CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
  const CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;
  const REFRESH_TOKEN = process.env.GOOGLE_REFRESH_TOKEN;

  if (!CLIENT_ID || !CLIENT_SECRET || !REFRESH_TOKEN) {
    console.error("Error: Missing GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, or GOOGLE_REFRESH_TOKEN in environment/dotenv.");
    console.error("Please ensure these are configured before running this test.");
    process.exit(1);
  }

  const testHtml = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Daily Relay Briefing Test</title>
    </head>
    <body>
      <main>
        <h1>Daily Relay Briefing</h1>
        <p>This is a test document generated by the <code>daily-relay</code> Google Drive publisher integration.</p>
        <h2>Status Check</h2>
        <ul>
          <li><strong>Date:</strong> ${new Date().toLocaleString()}</li>
          <li><strong>Target Format:</strong> Native Google Doc (converted from HTML)</li>
          <li><strong>Purpose:</strong> Validate the GDocs TTS "Audio, listen to this document" compatibility.</li>
        </ul>
        <p>If you see this document, the integration is working perfectly!</p>
      </main>
    </body>
    </html>
  `;

  console.log("Attempting to upload test HTML to Google Drive...");
  
  // Create or update a document named "Daily Relay Briefing (Test)"
  await publishBriefing(testHtml, { filename: 'Daily Relay Briefing (Test)' });
  
  console.log("=== Test execution finished ===");
}

runTest().catch(err => {
  console.error("Unhandled test error:", err);
  process.exit(1);
});
